export interface TrainingModule {
  id: number
  slug: string
  title: string
  categories: string[]
  bullets: string[]
  image: string
}

export const trainingModules: TrainingModule[] = [
  {
    id: 1,
    slug: "basic-business-management-methods",
    title: "Training No. 1: Basic Business Management Methods",
    categories: ["Management", "Foundations"],
    image: "/training-images/module1.jpg",
    bullets: [
      "Chapter 1: Introduction",
      "1.1: What is management?",
      "1.2: What is the need for management?",
      "1.3: Vertical & horizontal levels of management",
      "1.4: Role of management",
      "1.5: Management skills",
      "1.6: Decision making and its process",
      "1.7: The environment of management",
      "1.8: Functions of management",
      "Chapter 2: Planning Function",
      "2.1: What is planning?",
      "2.2: Basic questions of planning",
      "2.3: Types of plans",
      "2.4: Strategic plan - the big picture",
      "2.5: Tactical plan",
      "2.6: Operational plans",
      "Chapter 3: Organizing Function",
      "3.1: What does organizing mean?",
      "3.2: Organizational structure - vertical & horizontal",
      "3.3: Job description",
      "3.4: Organizing steps",
      "3.5: Approach to develop organization design",
      "3.6: Organizational authority and responsibility",
      "Chapter 4: Staffing Function",
      "4.1: What is staffing?",
      "4.2: Recruitment",
      "4.3: Selection of applicants & its process",
      "4.4: Training",
      "4.5: Performance appraisal systems and types",
      "Chapter 5: Leading (Directing) Function",
      "5.1: What is directing or leadership?",
      "5.2: Requirements of successful leadership",
      "5.3: Leadership styles",
      "5.4: Motivation",
      "5.5: Managing change",
      "5.6: Managing conflict and its strategies",
      "5.7: Communication",
      "Chapter 6: Controlling Function",
      "6.1: Nature and elements of control",
      "6.2: Steps of controlling",
      "6.3: Three types of management control",
      "6.4: Behavioural aspects of control",
    ],
  },
  {
    id: 2,
    slug: "overview-of-specific-management-areas",
    title: "Training No. 2: Overview of Specific Management Areas – by Selection of Institutions",
    categories: ["Finance", "Operations"],
    image: "/training-images/module2.jpg",
    bullets: [
      "CHAPTER 1 Finance-",
      "1.1. introduction",
      "1.2. cash receipt and disbursement procedures",
      "1.3. petty cash",
      "1.4. advances",
      "1.5. job request",
      "1.6. budgeting - mof guidelines",
      "CHAPTER 2 - PURCHASING",
      "2. purchasing and related activities",
      "2.1. source documents for purchases",
      "2.2. purchasing systems",
      "2.3. purchasing policy and procedures",
      "2.4. purchasing department records",
      "2.5. relations with other departments",
      "2.6 purchasing – guidelines",
      "CHAPTER 3 - LOGISTICS",
      "3. logistics and general service and related activities",
      "3.1. transportation unit",
      "3.2. mail services",
      "3.3. cleaning services",
      "3.4. security police",
      "CHAPTER 4 HUMAN RESOURCE MANAGEMENT (HRM)",
      "4. human resource management (HRM)",
      "4.1. background",
      "4.2. (HRM) general policies",
      "4.3. (HRM) policies & procedures for academic staff",
      "4.4. (HRM) policies & procedures for administrative staff",
    ],
  },
  {
    id: 3,
    slug: "basics-of-internal-management-accounting",
    title: "Training No. 3: Basics of Internal Management Accounting",
    categories: ["Accounting", "Finance"],
    image: "/training-images/module3.jpg",
    bullets: [
      "chapter 1: background to management accounting",
      "1.1 introduction",
      "1.2 management, financial, and cost accounting",
      "1.3 the management process and accounting",
      "1.4 management by exception",
      "1.5 functions of management accountant",
      "1.6 management accounting and service organizations",
      "chapter 2: cost-volume-profit (cvp) relationships",
      "2.1 importance of cost-volume-profit analysis (cvp analysis)",
      "2.2 variable costs and fixed costs",
      "2.3 break-even point – two techniques",
      "2.4 target net profit and incremental approach",
      "2.5 multiple changes in the key factors",
      "2.6 sales mix",
      "2.7 setting prices (for short run)",
      "chapter 3: relevant costs and special decisions",
      "3.1 the accountant’s role in special decision",
      "3.2 the meaning of relevance (relevant costs and revenues)",
      "3.3 one time only special order / special sales order",
      "3.4 deletion or addition of products or departments",
      "3.5 contribution to profits per unit of limiting factors",
      "3.6 make or buy and idle capacity",
      "3.7 make or buy and - unitization of facilities",
      "3.8 opportunity costs",
      "3.9 joint product costs and incremental costs",
      "3.10 incremental or differential revenue / costs",
      "3.11 irrelevance of past costs",
      "chapter 4: pricing decisions",
      "4.1 major influence on pricing",
      "4.2 product-cost categories and time horizon",
      "4.3 calculating product costs",
      "4.4 alternative long-run pricing approaches",
      "4.5 target costing for target pricing",
      "4.6 implementing target pricing and target costing",
      "4.7 cost-plus pricing",
      "4.8 cost plus target rate of return on investment",
      "chapter 5: the master budget: the overall plan",
      "5.1 advantages of budgets",
      "5.2 types of budgets",
      "5.3 classification of budgets",
      "5.4 basic steps in preparing cash budget",
      "chapter 6: standard costing",
      "6.1 setting of standards and analysis of variance",
      "6.2 purpose of standard costs",
      "6.3 comparison of budgets and standards",
      "6.4 setting standards",
      "chapter 7: flexible budgets",
      "7.1 introduction",
      "7.2 flexible budget comparison",
      "7.3 isolating the variance",
    ],
  },
  {
    id: 4,
    slug: "basics-of-internal-control-and-internal-auditing",
    title: "Training No. 4: Basics of Internal Control & Internal Auditing",
    categories: ["Governance", "Audit"],
    image: "/training-images/module4.jpg",
    bullets: [
      "1.2. Objectives of Internal Control",
      "1.5.1. Background",
      "1.6.1. Cash control",
      "2.1. Background",
      "1.3. Basic Concepts of Internal Control Systems",
      "1.5.2 Key Principles of internal control",
      "1.6.2. Internal Control over Accounts receivable",
      "2.2. Objectives of Internal Auditing",
      "1.4. Elements of Internal Control",
      "1.5.3 Why do company’s need internal control?",
      "1.6.3. Internal Control over Acquisition of goods",
      "2.3. The Organizational Set-up of Internal Auditing",
      "1.4.1. The Control Environment",
      "1.5.4. Why internal control interests’ auditors?",
      "1.6.4. Internal Control over Payments",
      "2.4. The Functional Role of Internal Auditing",
      "1.4.2. The Accounting System",
      "1.5.5. Types of internal controls:",
      "1.6.5. Internal Control over Inventory",
      "2.4.1. Relationship of internal auditing to other activities",
      "1.4.3. Control Procedures",
      "1.5.6. Understanding internal control system",
      "1.6.6. Internal Control over Payroll",
      "2.4.2. Relationship of internal auditing to top management",
      "1.5.7. Methods of ascertaining internal control system:",
      "1.6.7. Internal Control over Liabilities and capital",
      "2.4.3. Relationship of internal auditing to external auditor",
      "1.5.8. Recording and documenting internal control system",
      "2.5 Assessment of Internal Audit",
      "1.5.9. Evaluating internal control system:",
      "1.5.10 Limitations of internal control system:",
    ],
  },
  {
    id: 5,
    slug: "internal-control-over-cash-receivables-inventories",
    title: "Training No. 5: Internal Control over Cash, Receivables and Inventories",
    categories: ["Finance", "Operations"],
    image: "/training-images/module5.jpg",
    bullets: [
      "1.0 Cash Management and Control",
      "2.0. Management and control of Cash Collections",
      "3.0. Asset Management and Control",
      "1.1. Objectives of Cash management",
      "2.1. Reason for using credit sales",
      "3.1. Types of Properties",
      "1.2. Needs to Keep cash",
      "2.2. Credit policies, standards, analysis and terms",
      "3.2. Inventory Costs",
      "1.3. Administering cash collections and payments",
      "• 2.2.1. Credit Policies",
      "3.3. Procedures for Valuation",
      "1.4. Principles of internal control over cash",
      "• 2.2.2. Credit Standards",
      "3.4. Starting from Costs",
      "1.5. Bank account as control over cash",
      "• 2.2.3. Credit Analysis",
      "3.5. Inventory Control Systems",
      "1.6. Petty Cash Fund System as control over cash",
      "• 2.2.4. Loan Terms",
      "3.6. Economic Order Quantity, Optimum Order",
      "1.7. Voucher system as control over cash",
      "2.3. Credit Collection Procedures",
      "3.7. Estimating Value of Assets",
      "2.4. Promissory note",
      "2.5. Losses from Uncollectible Accounts",
    ],
  },
  {
    id: 6,
    slug: "project-cycle-management",
    title: "Training No. 6: Project Cycle Management",
    categories: ["Projects", "Strategy"],
    image: "/training-images/module6.jpg",
    bullets: [
      "Background to Project Management",
      "Overview of Project Cycle",
      "Business Project Feasibility Study",
      "3.4. Financial Analysis of Business Projects",
      "3.5. Concepts in valuation - Cash Flows Approach to Project Appraisal",
      "1.1. Project Definition",
      "• 2.1. Background to Project Cycle",
      "3.1. Pre-investment Study - Identification of project opportunities: -",
      "3.4.1. Objective of Business Projects financial analysis",
      "3.5.1. Present Value (PV):",
      "1.2. Objectives of projects",
      "• 2.2. Identifying Needs (Needs Assessment)",
      "3.2. Pre-feasibility Study",
      "3.4.2. Analysis of Investment Cost Estimates",
      "• 3.5.2. Internal Rate of Return (IRR)",
      "1.3. Stages in project development",
      "2.3. Designing a Project",
      "3.3. Feasibility Study",
      "3.4.2.1. Total Investment Costs:",
      "• 3.5.3. Payback period (PB)",
      "2.4. Project Implementation Management",
      "• 3.1.1. Role of Business Environment",
      "• 3.4.2.2. Fixed Investment Cost:",
      "• 3.5.4. Accounting rate of return (ARR)",
      "2.5. Monitoring Project Implementation",
      "• 3.1.2. Location, Site and Environmental Impacts",
      "• 3.4.2.3. Pre-Production Expenditure",
      "2.6. Controlling the Project Implementation",
      "• 3.1.3. Market Analysis and Marketing Concepts",
      "• 3.4.2.4. Working Capital",
      "2.7. Evaluating Project Performance",
    ],
  },
  {
    id: 7,
    slug: "marketing-management-training-7",
    title: "Training No. 7: Marketing Management",
    categories: ["Marketing"],
    image: "/training-images/module7.jpg",
    bullets: [
      "1.1. What is Marketing?",
      "2.1. Main Types of Demands Needs and wants",
      "3.1. Background to Marketing Strategy",
      "4.1. The basics steps in marketing a product",
      "1.2. What is Marketing Management?",
      "2.2. Main Tendency of Demands Needs and wants",
      "3.2. Customer-Driven Marketing Strategy",
      "4.2. The 10 Guiding Steps to Marketing Process",
      "1.3- Stages of Marketing Evolution",
      "Chapter 3. Background – to Marketing Strategy",
      "Step 1: Research Your Ideal Customer/Audience",
      "3.1. Background to Marketing Strategy",
      "Step 2: Analyse Your Market and Competition",
      "3.2. Customer-Driven Marketing Strategy",
      "Step 3: Evaluate Your Strengths, Weaknesses, Opportunities, & Threats (SWOT)",
      "Step 4: Research Your Distribution and Promotion Tactics",
      "Step 5: Know Your Financials",
      "Step 6: Set Marketing Objectives & Goals",
      "Step 7: Define Your Brand",
      "Step 8: Document Your Marketing Strategy",
      "Step 9: Build Content Strategy that will reach prospective Buyers",
      "Step 10: Execute Your Marketing Strategy",
    ],
  },
  {
    id: 8,
    slug: "marketing-management-training-8",
    title: "Training No. 8: Marketing Management",
    categories: ["Marketing", "Strategy"],
    image: "/training-images/module8.jpg",
    bullets: [
      "1.0 Background",
      "2.0 Marketing Strategy Process – The Path to Success",
      "3.0 Level Product Model",
      "1.1. Definition of Marketing – What is Marketing?",
      "2.1 – Step 1: Research your ideal Client/Audience",
      "3.1.1. Standards 1. Main Interest",
      "1.2. What is marketing management?",
      "2.2 – Step 2: Analyse your Market and Competition",
      "3.2. Standards 2. Basic Products",
      "1.3 – Levels of Market Development",
      "2.3 – Step 3: Examine Your Strengths – Opportunities, Weaknesses – Threats (SWOT Analysis)",
      "3.3. Standards 3. Expected Yield",
      "1.4. Core Concepts of Marketing",
      "2.4 – Step 4: Examine your Distribution and Promotion Techniques",
      "3.4. Step 4 – Added Product",
      "1.4.1. Needs and Requirements",
      "2.5 – Step 5: Know your Financial Skills",
      "1.4.2. Marketing Strategy and Process",
      "2.6 – Step 6: Set Marketing Objectives",
      "2.7 – Step 7: Define your Brand",
      "2.8 – Step 8: Send Your Marketing Strategy",
    ],
  },
  {
    id: 9,
    slug: "basics-of-budget-preparation",
    title: "Training No. 9: Basics of Budget Preparation",
    categories: ["Finance", "Planning"],
    image: "/training-images/module9.jpg",
    bullets: [
      "1.0: – Background Budget",
      "3.0: Evaluation and Control of Budget Performance",
      "4.0: Overall Budget (Activities and Finance)",
      "Step 1. – Sales Budget",
      "1.2. Types of Budgets",
      "3.1. Budget performance evaluation and control procedures",
      "4.1: Background of the budget summary",
      "Step 2 – Fundraising budget",
      "1.3. The Importance of Budget",
      "3.1.1. Background – Background",
      "4.2: Preparation of a summary budget.",
      "Step 3 – Purchase Budget",
      "2.0: Cash Budget (as part of the Comprehensive Master Budget)",
      "3.1.2. Physical [non-financial] Performance Reports",
      "4.2.1. Starting Balance Sheet Information",
      "Step 4 – Budgeted Payment for the purchase",
      "2.1. The Nature of the Budget Summary",
      "3.1.3. Financier Performance Reports",
      "4.2.2. Information on sales forecasting;",
      "Step 5 – Operating Expense Budget",
      "2.2. Advantages of Budgeting Money.",
      "4.2.3. Additional Information: (Company Policy)",
      "Step 6 – Budget Overhead Charges",
      "2.3. Main Budget Activities Money",
      "4.2.4. Questions – and Answers",
      "Step 7 – Income Statement Budget.",
      "Step 8 – Cash Budget.",
      "Step 9 – Budgeted balance sheet.",
    ],
  },
  {
    id: 10,
    slug: "financial-reports-and-interpretation",
    title: "Training No. 10: Financial Reports and Interpretation",
    categories: ["Finance", "Reporting"],
    image: "/training-images/module10.jpg",
    bullets: [
      "1.0: Background – Financial Statements",
      "2.0: Financial Reports and Interpretation",
      "2.2. – Relative Activity Relationships",
      "2.3. Relative relations of profit –",
      "2.4. Relative Debt Support Relationship",
      "1.1 Nature of Financial Reporting",
      "2.1. Relative Liquidity Relationship",
      "2.2.1. Speed of selling and Receiving money customers on Credit",
      "2.3.1. gross profit,",
      "2.4.1. Relative relationship of Debt to Total Capital or Working capital –",
      "1.2. Main Financial Reporting Tools",
      "2.1.1. Short term Liquidity – Current ratio",
      "2.2.2. Average collection time from Customers on Credit",
      "2.3.2. Net Profit,",
      "2.4.2. Relative Relationship of Debt to Total Assets",
      "2.1.2. Net Working Capital –",
    ],
  },
  {
    id: 11,
    slug: "strategic-management",
    title: "Training No. 11: STRATEGIC MANAGEMENT",
    categories: ["Strategy", "Leadership"],
    image: "/training-images/module11.jpg",
    bullets: [
      "Corporate Governance",
      "4.1. Corporate Mission and Policy",
      "5.1. Human Resource Management",
      "2. Management Concepts",
      "4.2. Strategy and Operational Planning",
      "5.1.1. individual ways of working",
      "3. General management model",
      "4.3. Organization",
      "5.1.2. Outcome",
      "3.1 Strategy",
      "4.4. Control and Reporting operations",
      "5.2. Short-term Goals",
      "3.2 Culture",
      "4.5. Annual Objectives",
      "5.3. Long-term Goals",
      "3.3 Executives",
      "3.4 System Structure",
    ],
  },
  {
    id: 12,
    slug: "internal-regulations-bylaws",
    title: "Training No. 12: Internal Regulations (BYLAWS)",
    categories: ["Governance", "Compliance"],
    image: "/training-images/module12.jpg",
    bullets: [
      "1- Document No. 1: General Internal Rules of the Company",
      "Article 6. Rights and Duties of Employees",
      "Article 11. Dissolution of Company",
      "Article 1. Official name, registered office and financial year.",
      "Article 7. Service and Equity Fees",
      "Article 12. Formation",
      "Article 2. Purpose of Company",
      "Article 8. Exclusion of Member",
      "Article 13. Institutional Governance Framework",
      "Article 3. Duties of the Company",
      "Article 9. General Assembly",
      "Article 14. Period of Application of Domestic Law",
      "Article4. Members",
      "Article 10. Function of Board of Directors",
      "Article 15. Founders of the Company",
      "Article 5. Rights and Duties of Members",
    ],
  },
  {
    id: 13,
    slug: "basic-meeting-procedures",
    title: "Training No. 13: Basic Meeting Procedures",
    categories: ["Operations", "Leadership"],
    image: "/training-images/module13.jpg",
    bullets: [
      "1.1. The purpose of the basic Meeting system",
      "2.1. Make sure there is a quorum",
      "3.1. Transparency by voting - majority proposal for resolution",
      "4.1. Agenda Topics in Order",
      "1.2. Basic Principles of Meeting",
      "2.2. Reports of Committees",
      "3.2. Our condemnation of the results of the vote",
      "4.2. Question or point of priority",
      "1.3. Preparation for a Meeting",
      "2.3. Agenda or subject of the meeting",
      "4.3. Point of Discipline",
      "2.4. Minutes of last meeting",
      "4.4. Breaks between Meetings",
      "2.5. New subject matter",
      "4.5. Ending the Meeting",
      "2.6. Information or announcements",
    ],
  },
]

